app/routes.php
<?php

Route::get('email-test', function(){
    //return View::make('partials.pages.email_confirmed');
    Mail::send('partials.missing', array('key' => 'value'), function($message)
    {
        $message->to('stackoverflow789@gmail.com', 'Anik Hasan')->subject('Welcome!');
    });
});


/*--------------------------------------------------------------------------
| Routes for Related to auth
--------------------------------------------------------------------------*/
Route::get('/sign-in', ['uses' => 'AuthController@getLogin']);
Route::post('/sign-in',['before' =>'csrf', 'uses' => 'AuthController@postLogin']);
Route::get('/sign-out', ['as' => 'users.logout', 'uses' => 'AuthController@logOut']);
Route::post('password-reset', ['before' =>'csrf', 'uses' => 'AuthController@changePassword']);

Route::get('activate-user/{user_id}/{code}', 'AuthController@activate_user');
Route::get('confirm-email/{user_id}/{code}', 'AuthController@confirmEmail');
Route::get('not-my-email/{user_id}/{code}', 'AuthController@activate_user');
Route::get('reject-registration/{user_id}/{code}', 'AuthController@rejectRegistration');
Route::post('/student-register', 'AuthController@postStudentRegistration');
Route::post('/employer-register', 'AuthController@postEmployerRegistration');
Route::post('/alumni-register', 'AuthController@postAlumniRegistration');

/*--------------------------------------------------------------------------
| Routes for administering Page's sections
--------------------------------------------------------------------------*/
Route::group(array('prefix' => 'pages','before' => 'adminOnly'), function() {
    Route::get('{id}/sections', ['uses' => 'SectionsController@index']);
    Route::get('/edit/{id}', ['uses' => 'PagesController@edit']);
    Route::post('/update/{id}', ['uses' => 'PagesController@update']);
});

/*--------------------------------------------------------------------------
| User administration for admin's only
--------------------------------------------------------------------------*/
Route::group(['prefix' => 'admin/', 'before' => 'adminOnly'], function(){

    Route::get('dashboard', [ 'as' => 'admin.dashboard', 'uses' => 'AdminController@showDashBoard']);

    Route::group(['prefix' => 'users'], function(){

        Route::get('/administrators', ['uses' => 'AdminController@index']);
        Route::get('/administrators/create', ['uses' => 'AdminController@create']);
        Route::post('/administrators/store', ['uses' => 'AdminController@store']);

        Route::get('/students/', ['as' => 'students.index', 'uses' => 'StudentsController@index']);
        Route::get('/employers/', ['as' => 'employers.index', 'uses' => 'EmployersController@index']);
        Route::get('/alumni/', ['as' => 'alumni.index', 'uses' => 'AlumnisController@index']);

        Route::get('/{uId}/block', 'UsersController@blockUser');
        Route::get('/{uId}/unblock', 'UsersController@unBlockUser');
    });
});


/*--------------------------------------------------------------------------
| All the User's profile related routes.
--------------------------------------------------------------------------*/
Route::get('/users/home', ['as' => 'users.home', 'before' => 'auth', 'uses' => 'AuthController@userHome']);
Route::get('users/{uId}/profile', ['as' => 'users.profile', 'uses' => 'UsersController@userProfile']);
Route::get('users/{uId}/profile/edit', ['as' => 'users.profile.edit', 'uses' => 'UsersController@edit']);
Route::put('users/{uId}/profile/update', ['as' => 'users.profile.update', 'uses' => 'UsersController@update']);
Route::get('users/{uId}/application-and-registrations', ['as' => 'users.applications', 'uses' => 'UsersController@applications']);


/*--------------------------------------------------------------------------
| Student's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/students/{id}/{name?}',[ 'as' => 'student.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'StudentsController@show']);
Route::get('/profile/students/{id}/{name?}/edit',[ 'as' => 'student.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'StudentsController@edit']);


/*--------------------------------------------------------------------------
| Alumni's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/alumni/{id}/{name?}',[ 'as' => 'alumni.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'AlumnisController@show']);
Route::get('/profile/alumni/{id}/{name?}/edit',[ 'as' => 'alumni.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'AlumnisController@edit']);


/*--------------------------------------------------------------------------
| Employer's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/employers/{id}/{name?}',[ 'as' => 'employer.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'EmployersController@show']);
Route::get('/profile/employers/{id}/{name?}/edit',[ 'as' => 'employer.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'EmployersController@edit']);


/*--------------------------------------------------------------------------
| news_updates related routes.
--------------------------------------------------------------------------*/
Route::resource('news_updates', 'NewsUpdatesController');
Route::get('news-and-events/{slug}' , [ 'as' => 'news_update.show', 'uses' => 'NewsUpdatesController@show']);


/*--------------------------------------------------------------------------
| jobs related routes.
--------------------------------------------------------------------------*/
Route::resource('jobs', 'JobsController');
Route::get('jobs/{jobId}/approve', ['before' => 'adminOnly', 'as' => 'jobs.approve', 'uses' => 'JobsController@approveJob']);
Route::get('jobs/{jobs}/export', ['as' => 'jobs.export', 'uses' => 'JobsController@exportRegistrants']);
Route::get('jobs/{job_id}/apply', ['as' => 'jobs.apply', 'uses' => 'JobsController@applyToJob']);
Route::get('jobs/{job_id}/close_registration', ['as' => 'jobs.close_registration', 'uses' => 'JobsController@closeRegistration']);
Route::get('jobs/{job_id}/open_registration', ['as' => 'jobs.open_registration', 'uses' => 'JobsController@openRegistration']);

Route::resource('users.saved_jobs', 'SavedJobsController');
Route::get('users/{uId}/saved_jobs/{jobId}/remove', ['as' => 'users.saved_jobs.remove', 'uses' => 'SavedJobsController@removeSavedJob']);
Route::get('users/{uId}/saved_jobs/{jobId}/save', ['as' => 'users.saved_jobs.save', 'uses' => 'SavedJobsController@saveJob']);


/*--------------------------------------------------------------------------
| PSDP Registration routes.
--------------------------------------------------------------------------*/
Route::resource('psdp_registrations', 'PsdpRegistrationsController');
Route::get('psdp_registrations/{psdpRegistrationId}/registrants', ['as' => 'psdp_registrations.registrants', 'uses' => 'PsdpRegistrationsController@getRegistrants']);
Route::get('psdp_registrations/{psdpRegistrationId}/enroll', ['as' => 'psdp_registrations.enroll', 'uses' => 'PsdpRegistrationsController@enroll']);
Route::get('psdp_registrations/{psdpRegistrationId}/export', ['as' => 'psdp.export', 'uses' => 'PsdpRegistrationsController@exportRegistrants']);
Route::get('psdp_registrations/{psdpRegistrationId}/close', ['as' => 'psdp_registration.close', 'uses' => 'PsdpRegistrationsController@closeRegistration']);
Route::get('psdp_registrations/{psdpRegistrationId}/complete', ['as' => 'psdp_registration.complete', 'uses' => 'PsdpRegistrationsController@makeCompleted']);


/*--------------------------------------------------------------------------
| Routes for departments.
--------------------------------------------------------------------------*/
Route::resource('departments', 'DepartmentsController');


/*--------------------------------------------------------------------------
| Routes for courses.
--------------------------------------------------------------------------*/
Route::resource('courses', 'CoursesController');


/*--------------------------------------------------------------------------
| Routes for organisations.
--------------------------------------------------------------------------*/
Route::resource('organisations', 'OrganisationsController');


/*--------------------------------------------------------------------------
| Routes for organisation types.
--------------------------------------------------------------------------*/
Route::resource('organisation_types', 'OrganisationTypesController');

/*--------------------------------------------------------------------------
| Routes for landing pages.
--------------------------------------------------------------------------*/
Route::get('/{slug?}', ['uses' => 'PagesController@show']);


/*--------------------------------------------------------------------------
| Routes for Page's sections
--------------------------------------------------------------------------*/
Route::resource('sections', 'SectionsController'); //handles the sections.update route.
Route::get('contents/{slug}', ['uses' => 'SectionsController@show']);


/*--------------------------------------------------------------------------
| Other routes.
--------------------------------------------------------------------------*/
App::missing(function($exception)
{
    return Response::view('partials.missing', array(), 404);
});

app/views/alumnies/edit.blade.php
@extends('admin.layouts.master')

@section('header')

@stop

@section('content')

<section class="hbox stretch">
    <section>
        <section class="vbox">
            <section class="scrollable padder">
                <section class="row m-b-md">
                    <div class="col-sm-12">
                        {{Form::open(['url' => URL::route('users.profile.update', $alumni->user->id), 'method' => 'PUT', 'files' => true])}}

                        <!--basic info -->
                        <section class="panel panel-default">
                            <header class="panel-heading font-bold">Edit Profile</header>
                            <div class="panel-body">
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label for="first_name">First Name : </label>
                                        <input type="text" name="first_name" value="{{$alumni->user->first_name}}" class="form-control"/>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label for="first_name">Last Name : </label>
                                        <input type="text" name="last_name" value="{{$alumni->user->last_name}}" class="form-control"/>
                                    </div>
                                </div>

                                <div class="col-xs-6">
                                  <label for="gender">Gender</label>
                                  <div class="form-group">
                                      <select name="gender" id="" class="form-control">
                                        <option value="m" @if($alumni->user->gender == 'm') selected @endif> Male </option>
                                        <option value="f" @if($alumni->user->gender == 'f') selected @endif> Female </option>
                                      </select>
                                  </div>
                                </div>

                                <div class="col-xs-6">
                                  <div class="form-group">
                                      <label for="phone_number">Email : </label>
                                      <input type="text" disabled name="email" value="{{$alumni->user->email}}" class="form-control"/>
                                  </div>
                                </div>

                                <div class="col-xs-6">
                                  <div class="form-group">
                                      <label for="phone_number">Phone Number : </label>
                                      <input type="text" name="phone_number" value="{{$alumni->user->phone_number}}" class="form-control"/>
                                  </div>
                                </div>

                                <div class="col-xs-6">
                                  <div class="form-group">
                                      <label for="cell_phone">cell phone Number : </label>
                                      <input type="text" name="cell_phone" value="{{$alumni->user->cell_phone}}" class="form-control"/>
                                  </div>
                                </div>

                                <div class="col-xs-6">
                                  <div class="form-group">
                                      <label for="password">Password (Leave blank if you don't want to change) : </label>
                                      <input type="password" name="password" class="form-control"/>
                                  </div>
                                </div>

                                <div class="col-xs-6">
                                    <label class="">Profile picture</label>
                                    <div class="form-group">
                                        <input name="profile_picture" type="file" class="filestyle" data-icon="false" data-classbutton="btn btn-default" data-classinput="form-control inline v-middle input-s" id="filestyle-0" style="position: fixed; left: -500px;"><div class="bootstrap-filestyle" style="display: inline;"><input type="text" class="form-control inline v-middle input-s" disabled=""> <label for="filestyle-0" class="btn btn-default"><span>Choose file</span></label></div>
                                    </div>
                                </div>
                            </div>
                        </section>
                        <!--basic info -->

                        <!-- professional profile -->
                        <section class="panel panel-default">
                            <header class="panel-heading font-bold">Professional Profile</header>
                            <div class="panel-body">
                                <div class="col-xs-12">
                                    <div class="form-group">
                                        <label for="first_name">URL : </label>
                                        <input type="text" name="url" value="{{$alumni->url}}" class="form-control"/>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label for="designation">Employment Organisation : </label>
                                        <input type="text" name="organisation" value="{{$alumni->organisation}}" class="form-control"/>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label for="designation">Post in the Organisation : </label>
                                        <input type="text" name="designation" value="{{$alumni->designation}}" class="form-control"/>
                                    </div>
                                </div>
                                <div class="col-xs-6">
                                    <div class="form-group">
                                        <label for="designation">I am Currently Unemployed :
                                            <input type="checkbox" name="employment_status" @if($alumni->employment_status == "on") checked @endif />
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </section>
                        <!-- professional profile -->

                        <button type="submit" class="btn btn-lg btn-default">Submit</button>
                        {{Form::close();}}
                    </div>
                </section>
            </section>
        </section>
    </section>
</section>

@stop

@section('footer')

@stop

app/views/alumnies/navigation.blade.php
<aside class="bg-black aside-md hidden-print" id="nav">
<section class="vbox">
<section class="w-f scrollable">
<div class="slim-scroll" data-height="auto" data-disable-fade-out="true" data-distance="0" data-size="10px" data-railOpacity="0.2">
<nav class="nav-primary hidden-xs">
  <div class="text-muted text-sm hidden-nav-xs padder m-t-sm m-b-sm">Administration</div>
  <ul class="nav nav-main" data-ride="collapse">
    <li  class="@if(!isset($jobs)) {{'active'}} @endif">
      <a href="{{URL::route('alumni.profile', Sentry::getUser()->id)}}" class="auto">
        <i class="i i-statistics icon">
        </i>
        <span class="font-bold">Profile</span>
      </a>
    </li>
    <li  class="@if(isset($jobs)) {{'active'}} @endif">
      <a href="{{URL::route('jobs.index');}}" class="auto">
        <i class="fa fa-briefcase icon">
        </i>
        <span class="font-bold">Jobs</span>
      </a>
    </li>
  </ul>
</div>
</section>

<footer class="footer hidden-xs no-padder text-center-nav-xs">
<a href="modal.lockme.html" data-toggle="ajaxModal" class="btn btn-icon icon-muted btn-inactive pull-right m-l-xs m-r-xs hidden-nav-xs">
<i class="i i-logout"></i>
</a>
<a href="#nav" data-toggle="class:nav-xs" class="btn btn-icon icon-muted btn-inactive m-l-xs m-r-xs">
<i class="i i-circleleft text"></i>
<i class="i i-circleright text-active"></i>
</a>
</footer>
</section>
</aside>

app/views/alumnies/show.blade.php
@extends('admin.layouts.master')

@section('header')
<link rel="stylesheet" href="<?php echo URL::to("");?>/assets/themify-icons/themify-icons.css" type="text/css" />
@stop

@section('action_bar')

@if($alumni->user->activated == 0)
<li class="hidden-xs">
  <a href="{{URL::to('activate-user/' . $alumni->user->id . '/' . $alumni->user->activation_code)}}">
    <i style="font-weight: 800; color:green" class="ti-check"></i>
  </a>
</li>
@endif

<li class="hidden-xs">
  <a href="{{URL::route('users.profile.edit', $alumni->user->id)}}">
    <i style="font-weight: 800; color:green" class="ti-pencil"></i>
  </a>
</li>


@stop

@section('content')

<section class="vbox">
    <section class="scrollable padder">
        <div class="row">
            <div class="col-xs-5">
                <div class="wrapper">
                    <section class="panel panel-default">
                        <h4 class="padder">{{$alumni->user->first_name}} {{$alumni->user->last_name}}</h4>
                        <ul class="list-group">
                            <li class="list-group-item">
                                Gender : {{$alumni->user->gender == 'm' ? "Male" : "Female"}}
                            </li>
                            <li class="list-group-item">
                                <i class="fa fa-envelope-o"></i> : <em>{{$alumni->user->email}}</em>
                            </li>
                            <li class="list-group-item">
                                <i class="fa fa-mobile-phone"></i> : <em>{{$alumni->user->cell_phone}}</em>
                            </li>
                            <li class="list-group-item">
                                <i class="fa fa-phone-square"></i> : <em>{{$alumni->user->phone_number}}</em>
                            </li>
                            <li class="list-group-item">
                                <i class="fa fa-globe"></i> : <em>{{$alumni->url}}</em>
                            </li>
                        </ul>
                    </section>
                    <section class="panel panel-default">
                        <h4 class="padder">Employment information</h4>
                        <ul class="list-group">
                            @if($alumni->employment_status == "on")
                                <li class="list-group-item">
                                    Unemployed
                                </li>
                            @else
                                <li class="list-group-item">
                                    <em>{{$alumni->organisation}}</em>
                                </li>
                                <li class="list-group-item">
                                    {{$alumni->designation}}
                                </li>
                            @endif
                        </ul>
                    </section>
                </div>
            </div>
            <div class="col-xs-4">
                <div class="wrapper ">
                    <img class="thumbnail" width="200px" height="180px" src="{{URL::to('files/users/pp/' . $alumni->user->profile_image )}}" alt="" />
                </div>
            </div>
        </div>
    </section>
</section>

@stop