app/routes.php
<?php

Route::get('email-test', function(){
    //return View::make('partials.pages.email_confirmed');
    Mail::send('partials.missing', array('key' => 'value'), function($message)
    {
        $message->to('stackoverflow789@gmail.com', 'Anik Hasan')->subject('Welcome!');
    });
});


/*--------------------------------------------------------------------------
| Routes for Related to auth
--------------------------------------------------------------------------*/
Route::get('/sign-in', ['uses' => 'AuthController@getLogin']);
Route::post('/sign-in',['before' =>'csrf', 'uses' => 'AuthController@postLogin']);
Route::get('/sign-out', ['as' => 'users.logout', 'uses' => 'AuthController@logOut']);
Route::post('password-reset', ['before' =>'csrf', 'uses' => 'AuthController@changePassword']);

Route::get('activate-user/{user_id}/{code}', 'AuthController@activate_user');
Route::get('confirm-email/{user_id}/{code}', 'AuthController@confirmEmail');
Route::get('not-my-email/{user_id}/{code}', 'AuthController@activate_user');
Route::get('reject-registration/{user_id}/{code}', 'AuthController@rejectRegistration');
Route::post('/student-register', 'AuthController@postStudentRegistration');
Route::post('/employer-register', 'AuthController@postEmployerRegistration');
Route::post('/alumni-register', 'AuthController@postAlumniRegistration');

/*--------------------------------------------------------------------------
| Routes for administering Page's sections
--------------------------------------------------------------------------*/
Route::group(array('prefix' => 'pages','before' => 'adminOnly'), function() {
    Route::get('{id}/sections', ['uses' => 'SectionsController@index']);
    Route::get('/edit/{id}', ['uses' => 'PagesController@edit']);
    Route::post('/update/{id}', ['uses' => 'PagesController@update']);
});

/*--------------------------------------------------------------------------
| User administration for admin's only
--------------------------------------------------------------------------*/
Route::group(['prefix' => 'admin/', 'before' => 'adminOnly'], function(){

    Route::get('dashboard', [ 'as' => 'admin.dashboard', 'uses' => 'AdminController@showDashBoard']);

    Route::group(['prefix' => 'users'], function(){

        Route::get('/administrators', ['uses' => 'AdminController@index']);
        Route::get('/administrators/create', ['uses' => 'AdminController@create']);
        Route::post('/administrators/store', ['uses' => 'AdminController@store']);

        Route::get('/students/', ['as' => 'students.index', 'uses' => 'StudentsController@index']);
        Route::get('/employers/', ['as' => 'employers.index', 'uses' => 'EmployersController@index']);
        Route::get('/alumni/', ['as' => 'alumni.index', 'uses' => 'AlumnisController@index']);

        Route::get('/{uId}/block', 'UsersController@blockUser');
        Route::get('/{uId}/unblock', 'UsersController@unBlockUser');
    });
});


/*--------------------------------------------------------------------------
| All the User's profile related routes.
--------------------------------------------------------------------------*/
Route::get('/users/home', ['as' => 'users.home', 'before' => 'auth', 'uses' => 'AuthController@userHome']);
Route::get('users/{uId}/profile', ['as' => 'users.profile', 'uses' => 'UsersController@userProfile']);
Route::get('users/{uId}/profile/edit', ['as' => 'users.profile.edit', 'uses' => 'UsersController@edit']);
Route::put('users/{uId}/profile/update', ['as' => 'users.profile.update', 'uses' => 'UsersController@update']);
Route::get('users/{uId}/application-and-registrations', ['as' => 'users.applications', 'uses' => 'UsersController@applications']);


/*--------------------------------------------------------------------------
| Student's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/students/{id}/{name?}',[ 'as' => 'student.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'StudentsController@show']);
Route::get('/profile/students/{id}/{name?}/edit',[ 'as' => 'student.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'StudentsController@edit']);


/*--------------------------------------------------------------------------
| Alumni's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/alumni/{id}/{name?}',[ 'as' => 'alumni.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'AlumnisController@show']);
Route::get('/profile/alumni/{id}/{name?}/edit',[ 'as' => 'alumni.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'AlumnisController@edit']);


/*--------------------------------------------------------------------------
| Employer's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/employers/{id}/{name?}',[ 'as' => 'employer.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'EmployersController@show']);
Route::get('/profile/employers/{id}/{name?}/edit',[ 'as' => 'employer.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'EmployersController@edit']);


/*--------------------------------------------------------------------------
| news_updates related routes.
--------------------------------------------------------------------------*/
Route::resource('news_updates', 'NewsUpdatesController');
Route::get('news-and-events/{slug}' , [ 'as' => 'news_update.show', 'uses' => 'NewsUpdatesController@show']);


/*--------------------------------------------------------------------------
| jobs related routes.
--------------------------------------------------------------------------*/
Route::resource('jobs', 'JobsController');
Route::get('jobs/{jobId}/approve', ['before' => 'adminOnly', 'as' => 'jobs.approve', 'uses' => 'JobsController@approveJob']);
Route::get('jobs/{jobs}/export', ['as' => 'jobs.export', 'uses' => 'JobsController@exportRegistrants']);
Route::get('jobs/{job_id}/apply', ['as' => 'jobs.apply', 'uses' => 'JobsController@applyToJob']);
Route::get('jobs/{job_id}/close_registration', ['as' => 'jobs.close_registration', 'uses' => 'JobsController@closeRegistration']);
Route::get('jobs/{job_id}/open_registration', ['as' => 'jobs.open_registration', 'uses' => 'JobsController@openRegistration']);

Route::resource('users.saved_jobs', 'SavedJobsController');
Route::get('users/{uId}/saved_jobs/{jobId}/remove', ['as' => 'users.saved_jobs.remove', 'uses' => 'SavedJobsController@removeSavedJob']);
Route::get('users/{uId}/saved_jobs/{jobId}/save', ['as' => 'users.saved_jobs.save', 'uses' => 'SavedJobsController@saveJob']);


/*--------------------------------------------------------------------------
| PSDP Registration routes.
--------------------------------------------------------------------------*/
Route::resource('psdp_registrations', 'PsdpRegistrationsController');
Route::get('psdp_registrations/{psdpRegistrationId}/registrants', ['as' => 'psdp_registrations.registrants', 'uses' => 'PsdpRegistrationsController@getRegistrants']);
Route::get('psdp_registrations/{psdpRegistrationId}/enroll', ['as' => 'psdp_registrations.enroll', 'uses' => 'PsdpRegistrationsController@enroll']);
Route::get('psdp_registrations/{psdpRegistrationId}/export', ['as' => 'psdp.export', 'uses' => 'PsdpRegistrationsController@exportRegistrants']);
Route::get('psdp_registrations/{psdpRegistrationId}/close', ['as' => 'psdp_registration.close', 'uses' => 'PsdpRegistrationsController@closeRegistration']);
Route::get('psdp_registrations/{psdpRegistrationId}/complete', ['as' => 'psdp_registration.complete', 'uses' => 'PsdpRegistrationsController@makeCompleted']);


/*--------------------------------------------------------------------------
| Routes for departments.
--------------------------------------------------------------------------*/
Route::resource('departments', 'DepartmentsController');


/*--------------------------------------------------------------------------
| Routes for courses.
--------------------------------------------------------------------------*/
Route::resource('courses', 'CoursesController');


/*--------------------------------------------------------------------------
| Routes for organisations.
--------------------------------------------------------------------------*/
Route::resource('organisations', 'OrganisationsController');


/*--------------------------------------------------------------------------
| Routes for organisation types.
--------------------------------------------------------------------------*/
Route::resource('organisation_types', 'OrganisationTypesController');

/*--------------------------------------------------------------------------
| Routes for landing pages.
--------------------------------------------------------------------------*/
Route::get('/{slug?}', ['uses' => 'PagesController@show']);


/*--------------------------------------------------------------------------
| Routes for Page's sections
--------------------------------------------------------------------------*/
Route::resource('sections', 'SectionsController'); //handles the sections.update route.
Route::get('contents/{slug}', ['uses' => 'SectionsController@show']);


/*--------------------------------------------------------------------------
| Other routes.
--------------------------------------------------------------------------*/
App::missing(function($exception)
{
    return Response::view('partials.missing', array(), 404);
});

app/models/NewsUpdate.php
<?php

class NewsUpdate extends \Eloquent {
	protected $fillable = [
        'title',
        'image',
        'content',
        'summery',
        'category',
        'attachment',
        'slug',
        'attachment_label',
        'published',
        'poster_id',
        'approver_id'
    ];


    public function poster()
    {
        return $this->belongsTo('User', 'poster_id');
    }

    public function approver()
    {
        return $this->belongsTo('User', 'approver_id');
    }
}

app/controllers/NewsUpdatesController.php
<?php

class NewsUpdatesController extends \BaseController {

    public function __construct(
        \cso\updates\NewsUpdateRepository $updates,
        \cso\departments\DepartmentRepository $departments, \cso\courses\CourseRepository $courses)
    {
        $this->news_updates = $updates;
        $this->departments = $departments;
        $this->courses = $courses;

        $this->beforeFilter('adminOnly', array('except' => 'show'));
    }

	/**
	 * Display a listing of the resource.
	 * GET /newsupdates
	 *
	 * @return Response
	 */
	public function index()
	{
		$news_updates = $this->news_updates->all();
        return View::make('news_updates.index', compact('news_updates'));
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /newsupdates/create
	 *
	 * @return Response
	 */
	public function create()
	{
		return View::make('news_updates.create');
	}

	/**
	 * Store a newly created resource in storage.
	 * POST /newsupdates
	 *
	 * @return Response
	 */
	public function store()
	{
		$post = $this->news_updates->store();
        if($post) {
            Session::put('successes', ['the news update has been created']);
            return Redirect::route('news_updates.index');
        }

        Session::put('errors' , $this->news_updates->get_errors());
        return Redirect::back();
	}

	/**
	 * Display the specified resource.
	 * GET /newsupdates/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($slug)
	{
        $content = $this->news_updates->findItemBySlug($slug); //cached

        if($content == NULL)
            App::abort(404);

        $relateds = $this->news_updates->getRelatedContents($content); //cached

        $departments = $this->departments->all(); //cached
        $courses = $this->courses->all(); //cached
        $news_updates = $this->news_updates->getTopFourNewsUpdates(); //cached
        $events = $this->news_updates->getTopFourNewsEvents(); //cached
        return View::make('news_updates.show', compact('content','relateds', 'courses', 'departments', 'news_updates', 'events'));
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /newsupdates/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$update = $this->news_updates->find($id);
        return View::make('news_updates.edit', compact('update'));
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /newsupdates/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		if($this->news_updates->update($id,null))
        {
            Session::put('successes', ['The content has been updated successfully']);
            return Redirect::back();
        }

        Session::put('errors', $this->news_updates->get_errors());
        return Redirect::back();
	}


	/**
	 * Remove the specified resource from storage.
	 * DELETE /newsupdates/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/views/news_updates/create.blade.php
@extends('admin.layouts.master')

@section('header')

<style type="text/css">

.scrollable {
    padding-bottom: 80px;
}

</style>

@stop

@section('content')
<section class="hbox stretch">
    <section>
        <section class="vbox">
            <section class="scrollable padder">
                <section class="row m-b-md">
                    <div class="col-sm-12">
                        <section class="panel panel-default">
                            <header class="panel-heading font-bold">New News update</header>
                            <div class="panel-body">
                                {{Form::open(['url' => URL::route('news_updates.store'), 'method' => 'post', 'files' => true])}}

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <input type="text" name="title" placeholder="Title" class="form-control"/>
                                        </div>
                                    </div>
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="">URI for this news and event</label>
                                            <input type="text" name="slug" placeholder="URI for this content" class="form-control"/>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="image">Featured Image for this peice of content?? (Optional)</label>
                                            <input type="file" name="image" class="form-control" placeholder="Attachment"/>
                                        </div>
                                    </div>
                                    
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="image">Body for this post??</label>
                                            <textarea name="content" id="" cols="30" rows="10" class="form-control"></textarea>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="summery">Summery of the content (Optional)</label>
                                            <textarea name="summery" id="" cols="20" rows="5" class="form-control"></textarea>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="summery">What kind of update is this?</label>
                                            <select name="category" class="form-control" id="">
                                                <option value="event">Event</option>
                                                <option value="update">News update</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="attachment">Would like to attach something like pdf, docs etc? (Optional)</label>
                                            <input type="file" name="attachment" class="form-control" placeholder="Attachment"/>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <input type="text" name="attachment_label" placeholder="Label for attached file (Optional, if you have attached anything)" class="form-control"/>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="">
                                                Keep this content published ? <input type="checkbox" checked name="published" value="1" />
                                            </label>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <button type="submit" class="btn btn-sm btn-default">Submit</button>
                                    </div>
                                {{Form::close();}}
                            </div>
                        </section>
                    </div>
                </section>
            </section>
        </section>
    </section>
</section>

@stop

@section('footer')

@stop

app/views/news_updates/edit.blade.php
@extends('admin.layouts.master')

@section('header')

<style type="text/css">

.scrollable {
    padding-bottom: 80px;
}

</style>

@stop

@section('content')
<section class="hbox stretch">
    <section>
        <section class="vbox">
            <section class="scrollable padder">
                <section class="row m-b-md">
                    <div class="col-sm-12">
                        <section class="panel panel-default">
                            <header class="panel-heading font-bold">New News update</header>
                            <div class="panel-body">
                                {{Form::open(['url' => URL::route('news_updates.update', $update->id), 'method' => 'put', 'files' => true])}}

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <input type="text" name="title" placeholder="Title" class="form-control" value="{{$update->title}}"/>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="">URI for this news and event</label>
                                            <input type="text" name="slug" placeholder="URI for this content" class="form-control" value="{{$update->slug}}"/>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="image">Featured Image for this peice of content?? (Optional)</label>
                                            <input type="file" name="image" class="form-control" placeholder="Attachment" />
                                        </div>
                                    </div>
                                    
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="image">Body for this post??</label>
                                            <textarea name="content" id="" cols="30" rows="10" class="form-control">{{$update->content}}</textarea>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="summery">Summery of the content (Optional)</label>
                                            <textarea name="summery" id="" cols="20" rows="5" class="form-control">{{$update->summery}}</textarea>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="summery">What kind of update is this?</label>
                                            <select name="category" class="form-control" id="">
                                                <option value="event" @if($update->category == 'event') selected @endif>Event</option>
                                                <option value="update"  @if($update->category == 'update') selected @endif>News update</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="attachment">Would like to attach something like pdf, docs etc? (Optional)</label>
                                            <input type="file" name="attachment" class="form-control" placeholder="Attachment"/>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <input value="{{$update->attachment_label}}" type="text" name="attachment_label" placeholder="Label for attached file (Optional, if you have attached anything)" class="form-control"/>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="">
                                                Keep this content published ? <input type="checkbox" @if($update->published == '1') checked @endif name="published" value="1" />
                                            </label>
                                        </div>
                                    </div>

                                    <div class="col-xs-12">
                                        <button type="submit" class="btn btn-sm btn-default">Submit</button>
                                    </div>
                                {{Form::close();}}
                            </div>
                        </section>
                    </div>
                </section>
            </section>
        </section>
    </section>
</section>

@stop

@section('footer')

@stop

app/views/news_updates/index.blade.php
@extends('admin.layouts.master')

@section('header')
<link rel="stylesheet" href="{{URL::to('assets/js/datatables/datatables.css')}}" type="text/css"/>
@stop

@section('action_bar')
@stop

@section('content')
<section class="vbox">
    <section class="scrollable padder">
      <div class="m-b-md">
          <h3 class="m-b-none">News update and events
            @if(\cso\utils\UserUtil::isAdmin() )
              <a class="btn btn-default btn-circle pull-right" href="{{URL::route('news_updates.create')}}">New news update or event</a>
            @endif
          </h3>
      </div>
            <section class="panel panel-default">
              <header class="panel-heading">
                Events and News updates
              </header>
              <div class="table-responsive">
                <table class="table table-striped m-b-none" data-ride="datatables">
                  <thead>
                    <tr>
                      <th>SL.</th>
                      <th>Title</th>
                      <th>Summery</th>
                      <th>Category</th>
                      <th>Published</th>
                      <th>Posted by</th>
                      <th>Approved by</th>
                      <th>Created on</th>
                    </tr>
                  </thead>
                  <tbody>
                      @foreach($news_updates as $update)
                          <tr>
                              <td>{{$update->id}}</td>
                                  <td><a href="{{URL::route('news_updates.edit', $update->id)}}">{{substr($update->title,0,20)}}</a></td>
                              <td>{{substr($update->summery,0,30)}}</td>
                              <td>{{$update->category == 'update' ? "News Update" : "Event" }}</td>
                              <td>{{$update->published == 1 ? "Published" : "Unpublished"}}</td>
                              <td>{{$update->poster->first_name}} {{$update->poster->last_name}}</td>
                              <td>{{$update->approver->first_name}} {{$update->approver->last_name}}</td>
                              <td>{{$update->created_at}}</td>
                          </tr>
                      @endforeach
                  </tbody>
                </table>
              </div>
            </section>
    </section>


</section>
@stop

@section('footer')
<script src="{{URL::to('assets/js/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{URL::to('assets/js/datatables/demo.js')}}"></script>

@stop