app/routes.php
<?php

Route::get('email-test', function(){
    //return View::make('partials.pages.email_confirmed');
    Mail::send('partials.missing', array('key' => 'value'), function($message)
    {
        $message->to('stackoverflow789@gmail.com', 'Anik Hasan')->subject('Welcome!');
    });
});


/*--------------------------------------------------------------------------
| Routes for Related to auth
--------------------------------------------------------------------------*/
Route::get('/sign-in', ['uses' => 'AuthController@getLogin']);
Route::post('/sign-in',['before' =>'csrf', 'uses' => 'AuthController@postLogin']);
Route::get('/sign-out', ['as' => 'users.logout', 'uses' => 'AuthController@logOut']);
Route::post('password-reset', ['before' =>'csrf', 'uses' => 'AuthController@changePassword']);

Route::get('activate-user/{user_id}/{code}', 'AuthController@activate_user');
Route::get('confirm-email/{user_id}/{code}', 'AuthController@confirmEmail');
Route::get('not-my-email/{user_id}/{code}', 'AuthController@activate_user');
Route::get('reject-registration/{user_id}/{code}', 'AuthController@rejectRegistration');
Route::post('/student-register', 'AuthController@postStudentRegistration');
Route::post('/employer-register', 'AuthController@postEmployerRegistration');
Route::post('/alumni-register', 'AuthController@postAlumniRegistration');

/*--------------------------------------------------------------------------
| Routes for administering Page's sections
--------------------------------------------------------------------------*/
Route::group(array('prefix' => 'pages','before' => 'adminOnly'), function() {
    Route::get('{id}/sections', ['uses' => 'SectionsController@index']);
    Route::get('/edit/{id}', ['uses' => 'PagesController@edit']);
    Route::post('/update/{id}', ['uses' => 'PagesController@update']);
});

/*--------------------------------------------------------------------------
| User administration for admin's only
--------------------------------------------------------------------------*/
Route::group(['prefix' => 'admin/', 'before' => 'adminOnly'], function(){

    Route::get('dashboard', [ 'as' => 'admin.dashboard', 'uses' => 'AdminController@showDashBoard']);

    Route::group(['prefix' => 'users'], function(){

        Route::get('/administrators', ['uses' => 'AdminController@index']);
        Route::get('/administrators/create', ['uses' => 'AdminController@create']);
        Route::post('/administrators/store', ['uses' => 'AdminController@store']);

        Route::get('/students/', ['as' => 'students.index', 'uses' => 'StudentsController@index']);
        Route::get('/employers/', ['as' => 'employers.index', 'uses' => 'EmployersController@index']);
        Route::get('/alumni/', ['as' => 'alumni.index', 'uses' => 'AlumnisController@index']);

        Route::get('/{uId}/block', 'UsersController@blockUser');
        Route::get('/{uId}/unblock', 'UsersController@unBlockUser');
    });
});


/*--------------------------------------------------------------------------
| All the User's profile related routes.
--------------------------------------------------------------------------*/
Route::get('/users/home', ['as' => 'users.home', 'before' => 'auth', 'uses' => 'AuthController@userHome']);
Route::get('users/{uId}/profile', ['as' => 'users.profile', 'uses' => 'UsersController@userProfile']);
Route::get('users/{uId}/profile/edit', ['as' => 'users.profile.edit', 'uses' => 'UsersController@edit']);
Route::put('users/{uId}/profile/update', ['as' => 'users.profile.update', 'uses' => 'UsersController@update']);
Route::get('users/{uId}/application-and-registrations', ['as' => 'users.applications', 'uses' => 'UsersController@applications']);


/*--------------------------------------------------------------------------
| Student's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/students/{id}/{name?}',[ 'as' => 'student.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'StudentsController@show']);
Route::get('/profile/students/{id}/{name?}/edit',[ 'as' => 'student.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'StudentsController@edit']);


/*--------------------------------------------------------------------------
| Alumni's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/alumni/{id}/{name?}',[ 'as' => 'alumni.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'AlumnisController@show']);
Route::get('/profile/alumni/{id}/{name?}/edit',[ 'as' => 'alumni.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'AlumnisController@edit']);


/*--------------------------------------------------------------------------
| Employer's Profile related routes.
--------------------------------------------------------------------------*/
Route::get('/profile/employers/{id}/{name?}',[ 'as' => 'employer.profile' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'EmployersController@show']);
Route::get('/profile/employers/{id}/{name?}/edit',[ 'as' => 'employer.profile.edit' ,'before' => ['canViewProfile', 'correctNameInTheURL'], 'uses' => 'EmployersController@edit']);


/*--------------------------------------------------------------------------
| news_updates related routes.
--------------------------------------------------------------------------*/
Route::resource('news_updates', 'NewsUpdatesController');
Route::get('news-and-events/{slug}' , [ 'as' => 'news_update.show', 'uses' => 'NewsUpdatesController@show']);


/*--------------------------------------------------------------------------
| jobs related routes.
--------------------------------------------------------------------------*/
Route::resource('jobs', 'JobsController');
Route::get('jobs/{jobId}/approve', ['before' => 'adminOnly', 'as' => 'jobs.approve', 'uses' => 'JobsController@approveJob']);
Route::get('jobs/{jobs}/export', ['as' => 'jobs.export', 'uses' => 'JobsController@exportRegistrants']);
Route::get('jobs/{job_id}/apply', ['as' => 'jobs.apply', 'uses' => 'JobsController@applyToJob']);
Route::get('jobs/{job_id}/close_registration', ['as' => 'jobs.close_registration', 'uses' => 'JobsController@closeRegistration']);
Route::get('jobs/{job_id}/open_registration', ['as' => 'jobs.open_registration', 'uses' => 'JobsController@openRegistration']);

Route::resource('users.saved_jobs', 'SavedJobsController');
Route::get('users/{uId}/saved_jobs/{jobId}/remove', ['as' => 'users.saved_jobs.remove', 'uses' => 'SavedJobsController@removeSavedJob']);
Route::get('users/{uId}/saved_jobs/{jobId}/save', ['as' => 'users.saved_jobs.save', 'uses' => 'SavedJobsController@saveJob']);


/*--------------------------------------------------------------------------
| PSDP Registration routes.
--------------------------------------------------------------------------*/
Route::resource('psdp_registrations', 'PsdpRegistrationsController');
Route::get('psdp_registrations/{psdpRegistrationId}/registrants', ['as' => 'psdp_registrations.registrants', 'uses' => 'PsdpRegistrationsController@getRegistrants']);
Route::get('psdp_registrations/{psdpRegistrationId}/enroll', ['as' => 'psdp_registrations.enroll', 'uses' => 'PsdpRegistrationsController@enroll']);
Route::get('psdp_registrations/{psdpRegistrationId}/export', ['as' => 'psdp.export', 'uses' => 'PsdpRegistrationsController@exportRegistrants']);
Route::get('psdp_registrations/{psdpRegistrationId}/close', ['as' => 'psdp_registration.close', 'uses' => 'PsdpRegistrationsController@closeRegistration']);
Route::get('psdp_registrations/{psdpRegistrationId}/complete', ['as' => 'psdp_registration.complete', 'uses' => 'PsdpRegistrationsController@makeCompleted']);


/*--------------------------------------------------------------------------
| Routes for departments.
--------------------------------------------------------------------------*/
Route::resource('departments', 'DepartmentsController');


/*--------------------------------------------------------------------------
| Routes for courses.
--------------------------------------------------------------------------*/
Route::resource('courses', 'CoursesController');


/*--------------------------------------------------------------------------
| Routes for organisations.
--------------------------------------------------------------------------*/
Route::resource('organisations', 'OrganisationsController');


/*--------------------------------------------------------------------------
| Routes for organisation types.
--------------------------------------------------------------------------*/
Route::resource('organisation_types', 'OrganisationTypesController');

/*--------------------------------------------------------------------------
| Routes for landing pages.
--------------------------------------------------------------------------*/
Route::get('/{slug?}', ['uses' => 'PagesController@show']);


/*--------------------------------------------------------------------------
| Routes for Page's sections
--------------------------------------------------------------------------*/
Route::resource('sections', 'SectionsController'); //handles the sections.update route.
Route::get('contents/{slug}', ['uses' => 'SectionsController@show']);


/*--------------------------------------------------------------------------
| Other routes.
--------------------------------------------------------------------------*/
App::missing(function($exception)
{
    return Response::view('partials.missing', array(), 404);
});

app/controllers/CoursesController.php
<?php

class CoursesController extends \BaseController {


    public function __construct(\cso\courses\CourseRepository $courses,
                                \cso\departments\DepartmentRepository $departments) {
        $this->courses = $courses;
        $this->departments = $departments;
        $this->beforeFilter('adminOnly');
    }
	/**
	 * Display a listing of the resource.
	 * GET /courses
	 *
	 * @return Response
	 */
	public function index()
	{
		$courses = $this->courses->all();
        $departments = $this->departments->all();
        return View::make('courses.index', compact('courses', 'departments'));
	}

	/**
	 * Show the form for creating a new resource.
	 * GET /courses/create
	 *
	 * @return Response
	 */
	public function create()
	{

	}

	/**
	 * Store a newly created resource in storage.
	 * POST /courses
	 *
	 * @return Response
	 */
	public function store()
	{
        if($this->courses->store()) {
            return Redirect::route('courses.index');
        } else {
            return Redirect::back()->withInputs();
        }
	}

	/**
	 * Display the specified resource.
	 * GET /courses/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 * GET /courses/{id}/edit
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		//
	}

	/**
	 * Update the specified resource in storage.
	 * PUT /courses/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		//
	}

	/**
	 * Remove the specified resource from storage.
	 * DELETE /courses/{id}
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		//
	}

}

app/views/courses/create.blade.php
/Applications/xampp/xamppfiles/htdocs/projects/cso/app/views/courses/create.blade.php

app/views/courses/edit.blade.php
/Applications/xampp/xamppfiles/htdocs/projects/cso/app/views/courses/edit.blade.php

app/views/courses/index.blade.php
@extends('admin.layouts.master')

@section('content')

<section class="vbox">
    <section class="scrollable padder">



<div class="m-b-md">
    <h3 class="m-b-none">Administer Courses and departments</h3>
</div>
  <div class="row">
    <div class="col-sm-6">
      <section class="panel panel-default">
        <header class="panel-heading">
          Courses
        </header>
        <table class="table table-bordered m-b-none">
          <thead>
            <tr>
              <th>SL.</th>
              <th>Name</th>
              <th width="70"></th>
            </tr>
          </thead>
          <tbody>

            @foreach($courses as $course)
            <tr>
              <td>{{$course->id}}</td>
              <td> {{$course->name}} </td>
              <td> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-pencil"></i></a> </td>
            </tr>
            @endforeach
            <tr>
                {{ Form::open(['url' => URL::route('courses.store')])}}
                <td colspan="2">
                   <input type="text" name="name" placeholder="Course Name" class="form-control"/>
                </td>
                <td>
                    <input type="submit" class="btn btn-sm btn-default"/>
                </td>
                {{ Form::close(); }}
            </tr>
          </tbody>
        </table>
      </section>
    </div>



    <div class="col-sm-6">
          <section class="panel panel-default">
            <header class="panel-heading">
              Departments
            </header>
            <table class="table table-bordered m-b-none">
              <thead>
                <tr>
                  <th>SL.</th>
                  <th>Name</th>
                  <th width="70"></th>
                </tr>
              </thead>
              <tbody>

                @foreach($departments as $d)
                <tr>
                  <td> {{$d->id}} </td>
                  <td> {{$d->name}} </td>
                  <td> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-pencil"></i></a> </td>
                </tr>
                @endforeach
                <tr>
                    {{ Form::open(['url' => URL::route('departments.store')])}}
                    <td colspan="2">
                       <input type="text" name="name" placeholder="Department Name" class="form-control"/>
                    </td>
                    <td>
                        <input type="submit" class="btn btn-sm btn-default"/>
                    </td>
                    {{ Form::close(); }}
                </tr>
              </tbody>
            </table>
          </section>
        </div>

  </div>

</section>
</section>


@stop

app/views/courses/show.blade.php
/Applications/xampp/xamppfiles/htdocs/projects/cso/app/views/courses/show.blade.php